# Generated by Django 5.0.1 on 2024-01-09 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Імʼя'),
        ),
    ]
